// Agent dispatcher. Picks a prompt template, calls Gemini (or Yahoo for Data),
// and normalizes the response into the `{ symbol, [agentId]: {...} }` payload
// shape `useAgentWorkflow` expects.

import { fetchMarketData } from '../marketData/index.js';
import { agentDefinitions, normalizeSymbol } from './definitions.js';
import { callGemini } from './geminiClient.js';
import { prompts } from './prompts.js';

/** @typedef {import('./types.js').AgentId} AgentId */
/** @typedef {import('./types.js').RunAgentOptions} RunAgentOptions */
/** @typedef {import('./types.js').RunAgentResult} RunAgentResult */

// Last-ditch fallback when Gemini returns text that can't be parsed as JSON
// even after the retry-with-hint pass. Keeps the dashboard usable instead of
// surfacing a hard error.
const plainTextPayload = (agentId, symbol, text) => {
  if (agentId === 'news') {
    return {
      news: text
        .split(/\n+/)
        .map((line) => line.replace(/^[-*\d.\s]+/, '').trim())
        .filter(Boolean)
        .slice(0, 3),
      sentimentScore: 50
    };
  }

  if (agentId === 'analysis') {
    return {
      valuation: 'Generated by Gemini',
      growthView: 'Generated by Gemini',
      marginView: 'Generated by Gemini',
      trendView: 'Generated by Gemini',
      analysisSummary: text.slice(0, 500)
    };
  }

  if (agentId === 'risk') {
    return {
      riskLevel: 'Moderate',
      risks: [text.slice(0, 220)],
      opportunities: ['See Gemini-generated analysis in the report section.']
    };
  }

  if (agentId === 'verifier') {
    return {
      status: 'warn',
      issues: [
        {
          severity: 'warning',
          claim: 'Verifier returned non-JSON output',
          problem: 'Could not parse structured verification result.',
          suggestion: text.slice(0, 220)
        }
      ]
    };
  }

  return {
    title: `${symbol} Gemini Investment Brief`,
    recommendation: 'Not rated',
    thesis: text.slice(0, 500),
    bullets: text
      .split(/\n+/)
      .map((line) => line.replace(/^[-*\d.\s]+/, '').trim())
      .filter(Boolean)
      .slice(0, 4)
  };
};

/**
 * Run a single agent and return its payload merged-shape result.
 * @param {AgentId} agentId
 * @param {string} symbol
 * @param {(message: string) => void} emitLog
 * @param {Partial<import('./types.js').WorkflowResults>} [context]
 * @param {AbortSignal} [signal]
 * @param {RunAgentOptions} [options]
 * @returns {Promise<RunAgentResult>}
 */
export const runAgent = async (agentId, symbol, emitLog, context = {}, signal, options = {}) => {
  const resolvedSymbol = normalizeSymbol(symbol);
  const agent = agentDefinitions.find((item) => item.id === agentId);

  // Data Agent intentionally bypasses Gemini — prices must come from a verified source.
  if (agentId === 'data') {
    emitLog(`${agent.label} started for ${resolvedSymbol}. Calling live market chart API...`);
    const { __cached, ...marketPayload } = await fetchMarketData(resolvedSymbol, signal);
    emitLog(`${agent.label} loaded live price and intraday chart data${__cached ? ' (cached)' : ''}.`);

    return {
      symbol: marketPayload.company.symbol,
      data: marketPayload
    };
  }

  // Pick the prompt: Report has a special "revision" mode when Verifier flagged blocking issues.
  let promptText;
  let logSuffix = '';
  if (agentId === 'report' && options.revisionFeedback) {
    promptText = prompts.reportRevision(resolvedSymbol, context, options.revisionFeedback);
    logSuffix = ' (revision)';
  } else {
    promptText = prompts[agentId](resolvedSymbol, context);
  }

  emitLog(`${agent.label} started for ${resolvedSymbol}${logSuffix}. Calling Gemini API...`);

  // Verifier and Report-revision must not re-ground — they reason on already-fetched facts.
  const callOptions = {};
  if (agentId === 'verifier' || (agentId === 'report' && options.revisionFeedback)) {
    callOptions.disableGrounding = true;
  }
  const { json, text, sources, __cached } = await callGemini(promptText, signal, callOptions);
  emitLog(`${agent.label} received Gemini response${__cached ? ' (cached)' : ''}${logSuffix}.`);

  // Defensive: if Gemini still wraps report inside a "report" field, unwrap it.
  let payload = json;
  if (agentId === 'report' && payload?.report && !payload.title) {
    payload = payload.report;
  }

  return {
    symbol: resolvedSymbol,
    [agentId]: {
      ...(payload || plainTextPayload(agentId, resolvedSymbol, text)),
      sources,
      rawText: payload ? undefined : text
    }
  };
};
